server {
    listen 80;
    listen [::]:80;
    server_name little-angle.mahispark.com;

    # Point to the exported static HTML directory
    root /var/www/little-angle-school/out;
    index index.html;

    # Gzip Compression
    gzip on;
    gzip_proxied any;
    gzip_comp_level 4;
    gzip_types text/css application/javascript image/svg+xml;

    location / {
        # Serve the requested file, if not found, assume it's a route and serve the .html, else 404
        try_files $uri $uri.html $uri/ /index.html;
    }

    # Cache static assets
    location /_next/static {
        expires 1y;
        add_header Cache-Control "public, max-age=31536000, immutable";
    }

    location /images {
        expires 1y;
        add_header Cache-Control "public, max-age=31536000, immutable";
    }
}
